language: node_js
node_js:
- '5'
branches:
  only:
  - master
install:
- npm install hexo-cli -g
- npm install
before_script:
- git config --global user.name 'weinot'
- git config --global user.email 'weinot@gmail.com'
- sed -i'' "s~https://github.com/weinot/weinot.github.io.git~https://${REPO_Token}@github.com/weinot/weinot.github.io.git~"
  _config.yml
script:
- npm run deploy
env:
  global:
    secure: YCGObAWd2+LpBKk+jSjv8nYK5Bg0p3vuZBkbMgkWUel9TgC4YQNVRJtCzk/1L5xpx5jPFPylPfc6JR6UWmdBrvN7mEDsQahYXIj3sfaOBu3ix1V4FBh073h3FOMc86I8bLTWa/o54cBHYLk5RAvIIFeJ4fZ6QywKGMh//9KgcXgvo1lk1P2TSRkSftpujUBJxnL8LGblfNchBTbpC0lX2mUy1P4hCmicibOg4r9i2vryOendQ/5VHeIFndsWKzOQJ8T/F5WMRUB3bk72C4W5gVPRJRKHckejv5F9h3M+7bFq390j3bWsUfvc3oJxMjO4p9bOeNx2D4Z8pU+zm2BdBS+inVKHKI8AGaTlJ3S+gVMU34yzUUR4VxvYoTySw5/g9zAPvtShzuVCsVXoL+cN8sZaZZfkUXd/QawKQGfJTjyUC0OdWq6hPRR8/AC0X5M8JaojcUbD93v+s0+l/Y6+eTsSUmaXYb1gpXzgWsFHZjLzlU/oB9FLTkVeQx3OgQPgCcqz0U6Ez6+lnvHBbfITKlb9RQFnYxoxruqFB0NKbUsBHogB7GokNKEj1K2tOz84v1AfU5IUAQt4B0SygwmDDWjCcZKDWErYTm8vWEiGolBEHL3KApeHH8mUROzigwi9A9ZB/0BuwcwFk35mfrdXp/iR7lcDwQk0se13oxAHRbk=
